'use strict';
let fineData=JSON.parse(document.getElementById('fineDataset').textContent);document.getElementById('fineDataset').remove();
const fineTileCache=new Map(),fineMaskCache=new Map();
function fineParams(p){return {current:p.get('current')!=='0',scope:p.get('current')==='0'?'full':'saved',mode:p.get('mode')||'walk',layer:Number(p.get('layer')||0),group:Number(p.get('group')||-1),radius:Number(p.get('radius')||2),minimum:Number(p.get('minimum')||3)}}
async function fineTile(scope,c,r){const key=scope+':'+Math.floor(r/128)+':'+Math.floor(c/128);if(fineTileCache.has(key))return fineTileCache.get(key);const encoded=fineData.tiles[key];if(!encoded)return {nodes:[],raw:[]};const bytes=Uint8Array.from(atob(encoded),x=>x.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));const value=JSON.parse(await new Response(stream).text());if(fineTileCache.size>=4)fineTileCache.delete(fineTileCache.keys().next().value);fineTileCache.set(key,value);return value}
async function fineImage(key){const im=new Image();await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=()=>reject(Error('缺少图层 '+key));im.src='data:image/png;base64,'+fineData.images[key]});return im}
async function fineMask(p){const o=fineParams(p),key=JSON.stringify(o);if(fineMaskCache.has(key))return fineMaskCache.get(key);const mode=o.mode==='spawn'?'spawn_'+o.radius+'_'+o.minimum:o.mode;const s=fineData.config.spec,canvas=document.createElement('canvas');canvas.width=s.columns;canvas.height=s.rows;const ctx=canvas.getContext('2d');ctx.fillStyle='black';ctx.fillRect(0,0,s.columns,s.rows);const k=o.scope+'_'+mode+'_L'+o.layer;if(fineData.images[k])ctx.drawImage(await fineImage(k),0,0);const pixels=ctx.getImageData(0,0,s.columns,s.rows);if(o.group>=0&&fineData.images[o.scope+'_groups_L'+o.layer]){const g=document.createElement('canvas');g.width=s.columns;g.height=s.rows;const gc=g.getContext('2d');gc.drawImage(await fineImage(o.scope+'_groups_L'+o.layer),0,0);const gs=gc.getImageData(0,0,g.width,g.height).data;for(let i=0;i<pixels.data.length;i+=4){if(gs[i]+gs[i+1]*256+gs[i+2]*65536!==o.group+1)pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=0}ctx.putImageData(pixels,0,0)}let count=0,bbox=[s.columns,s.rows,0,0];for(let r=0;r<s.rows;r++)for(let c=0;c<s.columns;c++){if(pixels.data[(r*s.columns+c)*4]){count++;bbox[0]=Math.min(bbox[0],c);bbox[1]=Math.min(bbox[1],r);bbox[2]=Math.max(bbox[2],c+1);bbox[3]=Math.max(bbox[3],r+1)}}if(!count)bbox=[0,0,s.columns,s.rows];const result={url:canvas.toDataURL('image/png'),meta:{white_cells:count,black_cells:s.columns*s.rows-count,bbox_cells:bbox,current_saved_navigation:o.current,group:o.group,layer:o.layer}};if(fineMaskCache.size>=2)fineMaskCache.delete(fineMaskCache.keys().next().value);fineMaskCache.set(key,result);return result}
async function fineMaskURL(p){return (await fineMask(p)).url}
function fineEligible(n,o){if(!n[14]||(o.group>=0&&n[6]!==o.group)||n[3]!==o.layer)return false;if(o.mode==='walk')return true;if(o.mode==='spawn')return n[o.radius===3?12:11]>=o.minimum;if(o.mode==='task')return Boolean(n[13]);return false}
async function fineJSON(url){const u=new URL(url,'http://offline.invalid'),p=u.searchParams,o=fineParams(p),s=fineData.config.spec;if(u.pathname==='/api/config')return fineData.config;if(u.pathname==='/api/mask')return (await fineMask(p)).meta;if(u.pathname==='/api/point'){const c=Number(p.get('c')),r=Number(p.get('r')),xy=[s.xmin_cm+(c+.5)*s.cell_cm,s.ymax_cm-(r+.5)*s.cell_cm],tile=await fineTile(o.scope,c,r),local=(r%128)*128+c%128;const raw=tile.raw.filter(x=>x[0]===local),ns=tile.nodes.filter(n=>n[1]===c&&n[2]===r);return {col:c,row:r,xy_cm:xy,empty_reason:raw.length?null:'没有此25厘米格心的原生准入记录；包络外或无导航，不代表确定物理障碍',surfaces:raw.map(x=>({nav_cm:[...xy,x[1]],feet_cm:[...xy,x[2]],reason_text:fineData.pool[x[3]],mesh:fineData.pool[x[5]],component:fineData.pool[x[4]],blockers:x[6].map(i=>fineData.pool[i])})),city_nodes:ns.map(n=>{const reasons=[];if(n[15])reasons.push('原1米失败范围保留隔离');if(!n[14])reasons.push('未建立到道路的双向细格连接');if(o.group>=0&&n[6]!==o.group)reasons.push('属于其他连通组');if(n[3]!==o.layer)reasons.push('属于其他叠置表面');if(o.mode==='encounter')reasons.push('此细格端点的双向视线尚未复测');if(!fineEligible(n,o)&&!reasons.length)reasons.push('未满足当前用途空间条件');return {id:n[0],c:n[1],r:n[2],layer:n[3],feet_cm:[...xy,n[5]],nav_cm:[...xy,n[4]],group:o.current?-1:n[6],saved_group:o.current?n[6]:-1,polys:n[9].map(i=>fineData.pool[i]),sample_ids:n[10],source_sample_scope:o.scope,component:fineData.pool[n[7]],mesh:fineData.pool[n[8]],assembly_site_count:n[o.radius===3?12:11],eligible:fineEligible(n,o),filter_reasons:reasons}})}}throw Error('不支持的离线读取')}
