'use strict';
let offlineData,offlineNodeIndex,offlineMaskCache=new Map();
const offlineReady=(async()=>{const text=document.getElementById('offlineDataset').textContent.trim();
 const binary=Uint8Array.from(atob(text),c=>c.charCodeAt(0));
 const stream=new Blob([binary]).stream().pipeThrough(new DecompressionStream('gzip'));
 offlineData=JSON.parse(await new Response(stream).text());document.getElementById('offlineDataset').remove();
 offlineNodeIndex=new Map();for(const n of offlineData.nodes){const key=(n[4]*offlineData.config.spec.rows+n[2])*offlineData.config.spec.columns+n[1];let list=offlineNodeIndex.get(key);if(!list)offlineNodeIndex.set(key,list=[]);list.push(n)}return true})();
function offlineParams(search){const p=search instanceof URLSearchParams?search:new URLSearchParams(search);return {mode:p.get('mode')||'walk',current:p.get('current')!=='0',group:Number(p.get('group')||-1),layer:Number(p.get('layer')||0),minimum:Number(p.get('minimum')||3),radius:Number(p.get('radius')||2)}}
function offlineBase(n,o){return n[4]===Number(o.current)&&Boolean(n[17])&&(o.group<0||n[7]===o.group)}
function offlineEligible(n,o){if(!offlineBase(n,o))return false;if(o.mode==='walk')return true;if(o.mode==='spawn')return n[o.radius===3?14:13]>=o.minimum;if(o.mode==='task')return Boolean(n[15]);if(o.mode==='encounter')return Boolean(n[16]);return false}
function offlineMask(search){const o=offlineParams(search),key=JSON.stringify(o);if(offlineMaskCache.has(key))return offlineMaskCache.get(key);const spec=offlineData.config.spec,c=document.createElement('canvas');c.width=spec.columns;c.height=spec.rows;const ctx=c.getContext('2d');ctx.fillStyle='black';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='white';let count=0,bbox=[c.width,c.height,0,0];for(const n of offlineData.nodes){if(n[3]!==o.layer||!offlineEligible(n,o))continue;ctx.fillRect(n[1],n[2],1,1);count++;bbox[0]=Math.min(bbox[0],n[1]);bbox[1]=Math.min(bbox[1],n[2]);bbox[2]=Math.max(bbox[2],n[1]+1);bbox[3]=Math.max(bbox[3],n[2]+1)}if(!count)bbox=[0,0,c.width,c.height];const value={url:c.toDataURL('image/png'),meta:{white_cells:count,black_cells:c.width*c.height-count,bbox_cells:bbox,mode:o.mode,current_saved_navigation:o.current,group:o.group,layer:o.layer}};offlineMaskCache.set(key,value);return value}
function offlineMaskURL(search){return offlineMask(search).url}
function offlineNode(n){const s=offlineData.config.spec,x=s.xmin_cm+(n[1]+.5)*s.cell_cm,y=s.ymax_cm-(n[2]+.5)*s.cell_cm;return {id:n[0],c:n[1],r:n[2],layer:n[3],scope:n[4]?'current':'survey',nav_cm:[x,y,n[5]],feet_cm:[x,y,n[6]],saved_group:n[4]?n[7]:-1,group:n[4]?n[8]:n[7],component:offlineData.pool[n[9]],mesh:offlineData.pool[n[10]],polys:n[11].map(i=>offlineData.pool[i]),sample_ids:n[12],assembly_site_count:n[13],sight_peers:[],saved:Boolean(n[4]),source_sample_scope:n[4]?'saved':'full'}}
function offlineJSON(url){const parsed=new URL(url,'http://offline.invalid'),p=parsed.searchParams,o=offlineParams(p),spec=offlineData.config.spec;
 if(parsed.pathname==='/api/config')return offlineData.config;
 if(parsed.pathname==='/api/mask')return offlineMask(p).meta;
 if(parsed.pathname==='/api/node')return offlineNode(offlineData.nodes[Number(p.get('id'))]);
 if(parsed.pathname==='/api/point'){const col=Number(p.get('c')),row=Number(p.get('r')),key=(Number(o.current)*spec.rows+row)*spec.columns+col;let lo=0,hi=offlineData.raw.length;while(lo<hi){const mid=(lo+hi)>>1;if(offlineData.raw[mid][0]<key)lo=mid+1;else hi=mid}let surfaces=[];for(let i=lo;i<offlineData.raw.length&&offlineData.raw[i][0]===key;i++){const r=offlineData.raw[i],reason=offlineData.pool[r[3]];surfaces.push({nav_cm:[spec.xmin_cm+(col+.5)*spec.cell_cm,spec.ymax_cm-(row+.5)*spec.cell_cm,r[1]],feet_cm:[spec.xmin_cm+(col+.5)*spec.cell_cm,spec.ymax_cm-(row+.5)*spec.cell_cm,r[2]],reason,reason_text:offlineData.reasons[reason]||reason,component:offlineData.pool[r[4]],mesh:offlineData.pool[r[5]],blockers:r[6].map(j=>offlineData.pool[j]),sample_id:r[7],polygon:offlineData.pool[r[8]],floor_walkable:Boolean(r[9]),city_support:Boolean(r[10])})}surfaces.sort((a,b)=>a.nav_cm[2]-b.nav_cm[2]);const nodes=(offlineNodeIndex.get(key)||[]).map(n=>{const d=offlineNode(n),reasons=[];if(n[18])reasons.push(offlineData.reasons.runtime_return_standing_capsule_overlap);if(!n[17])reasons.push('未建立到道路的双向格间连接');if(o.group>=0&&n[7]!==o.group)reasons.push('属于其他连通组');if(n[3]!==o.layer)reasons.push('属于其他叠置表面视图');const eligible=offlineEligible(n,o)&&n[3]===o.layer;if(!eligible&&!reasons.length)reasons.push('未满足当前用途的空间或视线条件');return {...d,eligible,filter_reasons:reasons,assembly_site_count:n[o.radius===3?14:13]}});return {col,row,xy_cm:[spec.xmin_cm+(col+.5)*spec.cell_cm,spec.ymax_cm-(row+.5)*spec.cell_cm],surfaces,city_nodes:nodes,empty_reason:surfaces.length?null:offlineData.reasons.no_navigation_or_coarse_unmeasured,profile:offlineData.config.profile,final_layout_selected:false}}
 throw Error('离线工具不支持该读取');}
